name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    branches:
      - staging
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, oracle-vps]

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/like-minded-fe-staging:latest
      - name: Delete Old docker container
        run: sudo docker rm -f like-minded-fe-staging-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name like-minded-fe-staging-container ${{ secrets.DOCKER_USERNAME }}/like-minded-fe-staging:latest
